#!/usr/bin/env python
"""
Author: Emily K Mallory and Ce Zhang
Date: 08/24/15
Contact: emily.mallory@stanford.edu

Refactored by: Tong Shu Li
Last updated: 2016-02-25
"""
import re

class Box(object):
    def __init__(self, s):
        """
        Left edge is smaller than right edge.
        Bottom edge is larger than top edge.
        """
        assert isinstance(s, str)

        # parse the bounding box generated by OCR
        m = re.search(r'p([0-9]*)l([0-9]*)t([0-9]*)r([0-9]*)b([0-9]*)', s)
        if m is not None:
            self.page = int(m.group(1))
            self.left = int(m.group(2))
            self.top = int(m.group(3))
            self.right = int(m.group(4))
            self.bottom = int(m.group(5))

        self.strform = s

    def __repr__(self):
        return self.strform

    def overlap(self, other):
        """Does this box overlap with another Box?"""

        assert isinstance(other, Box)
        horiz_total = max(self.right, other.right) - min(self.left, other.left)
        vert_total = max(self.bottom, other.bottom) - min(self.top, other.top)

        horiz_sum = (self.right - self.left) + (other.right - other.left)
        vert_sum = (self.bottom - self.top) + (other.bottom - other.top)

        return self.page == other.page and horiz_sum >= horiz_total and vert_sum >= vert_total
